apiVersion: v1
kind: Service
metadata:
  name: pgpool-svc
spec:
  type: NodePort
  sessionAffinity: None
  selector:
    app: pgpool
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
      nodePort: 32000
  
  